### ISSUE TITLE
Config file opening / closing tag mismatch

### ISSUE THREAD

**Issue by buvk** [shupershuff/D2rSPLoader#1]
config.xml contains:

```
<D2SPLLoaderConfig>
...
</D2SPLoaderConfig>
```

`<D2SPLLoaderConfig>` needs to changed to `<D2SPLoaderConfig>`

**Comment by shupershuff** [comment]
Thanks for letting me know, will sort this shortly.

**Comment by shupershuff** [comment]
Resolved in v1.1.0
